module.exports = [
 { title: "An American Werewolf in London", description: "The film tells the story of two American students while on a walking backpacking holiday tour of Britain are attacked by a werewolf in England that none of the locals will admit exists.", genre: "Triller, Horror, Comedy", year: 1981, movie_director: "John Landis", posterurl: "https://steamcdn-a.akamaihd.net/steam/apps/427380/header.jpg" },
 { title: "Batman v Superman: Dawn of Justice", description: "Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.", genre: "Action, Adventure, Sci-Fi", year: 2016, movie_director: "Zack Snyder", posterurl: "https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" },
 { title: "Deep Blue Sea", description: "Searching for a cure to Alzheimer's disease, a group of scientists on an isolated research facility become the prey, as a trio of intelligent sharks fight back.", genre: "Action, Adventure, Sci-Fi, Thriller", year: 1999, movie_director: "Renny Harlin", posterurl: "https://m.media-amazon.com/images/M/MV5BZWM0NjVkOGYtMjk5Mi00NGVmLWE3NDMtMDQ3ZjdjMDcwYzdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg" },
 { title: "Enter the Dragon", description: "A martial artist agrees to spy on a reclusive crime lord using his invitation to a tournament there as cover.", genre: "Action, Crime, Drama, Thriller", year: 1973, movie_director: "Robert Clouse", posterurl: "https://m.media-amazon.com/images/M/MV5BNGZiMTkyNzQtMDdmZi00ZDNkLWE4YTAtZGNlNTIzYzQyMGM2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg" },
 { title: "Essay from the deserted land", description: "Nature sometime bestows favor on who is fortunate to take it when all hope is lost", genre: "Adventure", year: 2019, movie_director: "Fred Gaius", posterurl: "https://" },
 { title: "Game of Thrones", description: "Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.", genre: "Action, Adventure, Drama, Fantasy, Romance", year: 2011, movie_director: "Alan Taylor, Brian Kirk", posterurl: "https://m.media-amazon.com/images/M/MV5BMjA5NzA5NjMwNl5BMl5BanBnXkFtZTgwNjg2OTk2NzM@._V1_SX300.jpg" },
 { title: "Hard Way, The Only Way", description: "Americans thinks life is easy until this type of movie teaches otherwise", genre: "Action, Drama", year: 2001, movie_director: "Bob Willis", posterurl: "https://" },
 { title: "Hercules Saga", description: "Greek god and goddesses fight of revenge", genre: "Legend, Mythology", year: 2014, movie_director: "Dwayne Johnson", posterurl: "https://www.dwane.com" },
 { title: "Keanu Reeves: Journey to Success", description: "No actor's private life is more guarded and more mysterious than Keanu Reeves. Within it rests a world filled with rumors and tragedy, love and loss, fortune and fame. But now for the first...", genre: "Documentary", year: 2003, movie_director: "Brandon Christopher", posterurl: "https://m.media-amazon.com/images/M/MV5BMTc2NjAyNDkxOF5BMl5BanBnXkFtZTcwNTEyMzQyMQ@@._V1_SX300.jpg" },
 { title: "kukuruku Rooster", description: "Wherever there is iyokhokho with ivbiokhokhuko there is okporhu no muehin", genre: "Legend, Myth", year: 2017, movie_director: "Akobe Izighadan", posterurl: "https://www.akobefilms.com" },
 { title: "Love after love", description: "When there is a generation shift, the only thing left of a septagenarian is to start feeling like a teenager and love again", genre: "Love, Romance", year: 2016, movie_director: "Richard Davis", posterurl: "https://" },
 { title: "No Longer at Ease", description: "Once in Africa before the British Colonization, there was a kingdom called 'The Benin Kingdom'", genre: "Documentary", year: 1969, movie_director: "Chinue Achebe", posterurl: "https://" },
 { title: "Pretty Woman", description: "When a lonlely girl without education gets hooked up with the rich and most educated", genre: "Drama", year: 1994, movie_director: "Harry Clean", posterurl: "https://www.harryclean.com" },
 { title: "Snake in Monkey Shadow", description: "A tales in China of how a litte boy became a Superstar", genre: "Martial Arts, Drama", year: 1978, movie_director: "Raymond Cho", posterurl: "https://" },
 { title: "The Ghost and the Darkness", description: "A bridge engineer and an experienced old hunter begin a hunt for two lions after they start attacking local construction workers.", genre: "Adventure, Drama, Thriller", year: 1996, movie_director: "Stephen Hopkins", posterurl: "https://m.media-amazon.com/images/M/MV5BNWQ4NDRiMWItNGI5Yi00N2U1LTlkMGQtM2VjMzdkZTU0YzYyXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_SX300.jpg" },
 { title: "Too Easy to Take", description: "The simple-minded soon realises that life needs hardwork.", genre: "Action, Drama", year: 2015, movie_director: "Misop Collins", posterurl: "https://" }
];